### 1. CREATE a new task
POST http://localhost:8080/tasks
Content-Type: application/json
Authorization: Basic admin password321

{
  "title": "Learn Spring Boot",
  "isComplete": false
}

### 2. CREATE a second task
POST http://localhost:8080/tasks
Authorization: Basic user 93af4066-3343-40d8-9df5-099aedf2a453
Content-Type: application/json

{
  "title": "Write HTTP tests",
  "isComplete": true
}


### 3. GET all tasks
GET http://localhost:8080/tasks
Authorization: Basic user 93af4066-3343-40d8-9df5-099aedf2a453


### 4. UPDATE a task
PUT http://localhost:8080/tasks/1
Content-Type: application/json

{
  "title": "MASTER Spring Boot",
  "isComplete": true
}


### 5. GET all tasks (to confirm the update)
GET http://localhost:8080/tasks


### 6. DELETE a task
DELETE http://localhost:8080/tasks/1


### 7. GET all tasks (to confirm the delete)
GET http://localhost:8080/tasks


### 8. GET a task that does NOT exist
GET http://localhost:8080/tasks/99


### 9. DELETE a task that does NOT exist
DELETE http://localhost:8080/tasks/99